### ISSUE TITLE
macOS Catalina compatibility

### ISSUE THREAD

**Issue by nervousapps** [PaulStoffregen/Arduino-1.8.9-Teensyduino#2]
Hi, the installation is not possible on macOS Catalina 10.15 as it is necessary to install the PR related by this issue  https://github.com/arduino/Arduino/pull/8976, which is 1.10.0, to have the 64bit compatibility. 

Is there any works about that ?

Thanks in advance.

**Comment by PaulStoffregen** [comment]
This a not a bug in Teensyduino.  Presumably Arduino will publish 1.8.10 before Apple releases their new OS.  As always, we will publish a new version of Teensyduino when Arduino publishes non-beta software.
